[2023-08-30T20:01:30.417+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_migration.install_required_packages manual__2023-08-30T20:00:01.152599+00:00 [queued]>
[2023-08-30T20:01:30.428+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_migration.install_required_packages manual__2023-08-30T20:00:01.152599+00:00 [queued]>
[2023-08-30T20:01:30.429+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-30T20:01:30.439+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): install_required_packages> on 2023-08-30 20:00:01.152599+00:00
[2023-08-30T20:01:30.445+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2023-08-30T20:01:30.448+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_migration', 'install_required_packages', 'manual__2023-08-30T20:00:01.152599+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/data_mig_dag.py', '--cfg-path', '/tmp/tmp7r2tt06a']
[2023-08-30T20:01:30.453+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask install_required_packages
[2023-08-30T20:01:30.490+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-08-30T20:01:30.533+0000] {task_command.py:415} INFO - Running <TaskInstance: data_migration.install_required_packages manual__2023-08-30T20:00:01.152599+00:00 [running]> on host 3938d7abd9ff
[2023-08-30T20:01:30.611+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_migration' AIRFLOW_CTX_TASK_ID='install_required_packages' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T20:00:01.152599+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T20:00:01.152599+00:00'
[2023-08-30T20:01:30.615+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-30T20:01:30.617+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip install sodapy geoalchemy2']
[2023-08-30T20:01:30.630+0000] {subprocess.py:86} INFO - Output:
[2023-08-30T20:01:31.643+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-08-30T20:01:32.031+0000] {subprocess.py:93} INFO - Collecting sodapy
[2023-08-30T20:01:32.401+0000] {subprocess.py:93} INFO -   Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
[2023-08-30T20:01:32.452+0000] {subprocess.py:93} INFO - Collecting geoalchemy2
[2023-08-30T20:01:32.474+0000] {subprocess.py:93} INFO -   Downloading GeoAlchemy2-0.14.1-py3-none-any.whl (54 kB)
[2023-08-30T20:01:32.493+0000] {subprocess.py:93} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.0/55.0 kB 3.1 MB/s eta 0:00:00
[2023-08-30T20:01:32.496+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests>=2.28.1 in /home/***/.local/lib/python3.8/site-packages (from sodapy) (2.31.0)
[2023-08-30T20:01:32.501+0000] {subprocess.py:93} INFO - Requirement already satisfied: packaging in /home/***/.local/lib/python3.8/site-packages (from geoalchemy2) (23.1)
[2023-08-30T20:01:32.503+0000] {subprocess.py:93} INFO - Requirement already satisfied: SQLAlchemy>=1.4 in /home/***/.local/lib/python3.8/site-packages (from geoalchemy2) (1.4.49)
[2023-08-30T20:01:32.510+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.28.1->sodapy) (3.4)
[2023-08-30T20:01:32.511+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3<3,>=1.21.1 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.28.1->sodapy) (1.26.16)
[2023-08-30T20:01:32.513+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.28.1->sodapy) (3.2.0)
[2023-08-30T20:01:32.514+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests>=2.28.1->sodapy) (2023.7.22)
[2023-08-30T20:01:32.552+0000] {subprocess.py:93} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from SQLAlchemy>=1.4->geoalchemy2) (2.0.2)
[2023-08-30T20:01:35.211+0000] {subprocess.py:93} INFO - Installing collected packages: sodapy, geoalchemy2
[2023-08-30T20:01:35.282+0000] {subprocess.py:93} INFO - Successfully installed geoalchemy2-0.14.1 sodapy-2.2.0
[2023-08-30T20:01:35.551+0000] {subprocess.py:93} INFO - 
[2023-08-30T20:01:35.553+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.2.1
[2023-08-30T20:01:35.554+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-08-30T20:01:35.741+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-30T20:01:35.768+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_migration, task_id=install_required_packages, execution_date=20230830T200001, start_date=20230830T200130, end_date=20230830T200135
[2023-08-30T20:01:35.797+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T20:01:35.822+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
